name: cron

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        runtime:
          - wasmer
          - wasmtime

    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: false

      - name: Clone output repository
        uses: actions/checkout@v2
        with:
          repository: caspervonb/wasi-test-results
          path: results
          token: ${{ secrets.PAT }}

      - name: Setup wasmer
        if: matrix.runtime == 'wasmer'
        run: |-
          curl https://get.wasmer.io -sSfL | sh
          echo "$HOME/.wasmer/bin" >> $GITHUB_PATH

      - name: Setup wasmtime
        if: matrix.runtime == 'wasmtime'
        run: |-
          curl https://wasmtime.dev/install.sh -sSf | bash
          echo "$HOME/.wasmtime/bin" >> $GITHUB_PATH

      - name: Run tests
        run: |-
          python test.py ${{ matrix.runtime }} > results/${{ matrix.runtime }}.json

      - name: Commit to results repository
        run: |-
          cd results
          git config user.name "Casper Beyer"
          git config user.email "caspervonb@pm.me"
          git add .
          git commit -m "Update results"
          git push
