name: cron

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        runtime:
          - wasmer
          - wasmtime

    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: false

      - name: Clone results repository
        uses: actions/checkout@v2
        with:
          repository: caspervonb/wasi-test-results
          path: results
          token: ${{ secrets.PAT }}

      - name: Setup ${{ matrix.runtime }}
        uses: .github/actions/setup-${{ runtime }}

      - name: Run tests
        run: |-
          python test.py ${{ matrix.runtime }} > results/${{ matrix.runtime }}.json

      - name: Commit to results repository
        run: |-
          cd results
          git config user.name "Casper Beyer"
          git config user.email "caspervonb@pm.me"
          git add .
          git commit -m "Update results"
          git push
